export const userInputs = [
  {
    id: 1,
    name : 'username',
    label: "Username",
    type: "text",
    placeholder: "john_doe",
  },
  {
    id: 2,
    name : 'surname',
    label: "Name and surname",
    type: "text",
    placeholder: "John Doe",
  },
  {
    id: 3,
    name : 'email',
    label: "Email",
    type: "mail",
    placeholder: "john_doe@gmail.com",
  },
  {
    id: 4,
    name : 'phone',
    label: "Phone",
    type: "text",
    placeholder: "+1 234 567 89",
  },
  {
    id: 5,
    name : 'password',
    label: "Password",
    type: "password",
  },
  {
    id: 6,
    name : 'address',
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
  },

  {
    id: 7,
    name : 'country',
    label: "Country",
    type: "text",
    placeholder: "USA",
  },
];

export const productInputs = [
  {
    id: 1,
    name : 'title',
    label: "Title",
    type: "text",
    placeholder: "Apple Macbook Pro",
  },
  {
    id: 2,
    name : 'description',
    label: "Description",
    type: "text",
    placeholder: "Description",
  },
  {
    id: 3,
    name : 'category',
    label: "Category",
    type: "text",
    placeholder: "Computers",
  },
  {
    id: 4,
    name : 'price',
    label: "Price",
    type: "text",
    placeholder: "100",
  },
  {
    id: 5,
    name : 'stock',
    label: "Stock",
    type: "text",
    placeholder: "in stock",
  },
];

export const vehicleInputs = [
  {
    id: 1,
    name : 'vehicleName',
    label: "Vehicle Name",
    type :'text',
    placeholder: "Apple Macbook Pro",
  },
  {
    id: 2,
    name : 'type',
    label: "Type",
    type :'text',
    placeholder: "Car",
  },
  {
    id: 3,
    name : 'status',
    label: "Status",
    type: "text",
    placeholder: "Active",
  },
  {

    id: 4,
    name : 'ownership',
    label: "Ownership",
    type: "text",
    placeholder: "owned",
  },
  {
    id: 5,
    name : 'label',
    label: "label",
    type: "text",
    placeholder: "la",
  },
  {
    id: 6,
    name : 'vin',
    label: "VIN",
    type: "text",
    placeholder: "vin",
  },
  {
    id: 7,
    name : 'make',
    label: "make",
    type: "text",
    placeholder: "Toyota",
  },
  {
    id: 8,
    name : 'model',
    label: "Model",
    type: "text",
    placeholder: "Model",
  },
  {
    id: 9,
    name : 'group',
    label: "Group",
    type: "text",
    placeholder: "management",
  },
  {
    id: 10,
    name : 'year',
    label: "year",
    type: "date",
  },
  {
    id: 11,
    name : 'currentMeter',
    label: "current_meter",
    type: "text",
    placeholder :'205004 mi'
  },
  {
    id: 12,
    name : 'licensePlate',
    label: "License Plate",
    type: "text",
    placeholder :'6TRJ244	'
  },
];

export const equipmentInputs = [
  {
    id: 1,
    name : 'serailnumber',
    label: "Serail Number",
    type: "number",
    placeholder: "11523",
  },
  {
    id: 2,
    name : 'linked_vehicles',
    label: "Linked_vehicles",
    type: "number",
    placeholder: "2",
  },
  {
    id: 3,
    name : 'type',
    label: "Type",
    type: "text",
    placeholder: "Telementry Device",
  },
  {
    id: 4,
    name : 'labels',
    label: "Labels",
    type: "number",
    placeholder: "7",
  },
  {
    id: 5,
    name : 'current_assignee',
    label: "current_assignee",
    type: "text",
    placeholder: "Manu raju",
  },
  {
    id: 6,
    name : 'open_issues',
    label: "open_issues",
    type: "text",
    placeholder: "registration",
  },
  {
    id: 7,
    name : 'vehicle_operator',
    label: "vehicle_operator",
    type: "text",
    placeholder: "kadu",
  },
  {
    id: 8,
    name : 'status',
    label: "status",
    type: "text",
    placeholder: "active",
  },
  {
    id: 9,
    name : 'name',
    label: "name",
    type: "text",
    placeholder: "Engine",
  },
  {
    id: 10,
    name : 'brand',
    label: "brand",
    type: "text",
    placeholder: "toyota",
  },
  {
    id: 11,
    name : 'group',
    label: "group",
    type: "text",
    placeholder: "warehouse",
  },
  {
    id: 12,
    name : 'watchers',
    label: "watchers",
    type: "text",
    placeholder: "john",
  },
  {
    id: 13,
    name : 'id',
    label: "Id",
    type: "number",
    placeholder: "enter id",
  },
];
